In [1]:
import numpy as np

In [2]:
arr = np.arrange(0,11)

AttributeError: module 'numpy' has no attribute 'arrange'

In [3]:
arr = np.arange(0,11)

In [4]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
arr = np.arange(0,11,3)

In [6]:
arr

array([0, 3, 6, 9])

In [7]:
np.zeros(3)

array([0., 0., 0.])

In [8]:
np.ones(2)

array([1., 1.])

In [10]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [14]:
np.linspace(0,50,5)

array([ 0. , 12.5, 25. , 37.5, 50. ])

In [15]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [33]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [24]:
arr = np.random.randint(0,50,10)

In [25]:
arr

array([19,  2, 20, 47, 41, 40, 14, 11,  1, 40])

In [26]:
arr.max()

47

In [27]:
arr.argmax()

3

In [28]:
arr.min()

1

In [29]:
arr.argmin()

8

In [31]:
arr.shape

(10,)

In [38]:
arr2 = arr.reshape(2,5)

In [39]:
arr2

array([[19,  2, 20, 47, 41],
       [40, 14, 11,  1, 40]])

In [40]:
arr2.shape

(2, 5)

In [43]:
arr2.dtype

dtype('int32')

In [44]:
arr

array([19,  2, 20, 47, 41, 40, 14, 11,  1, 40])

In [45]:
arr[2]

20

In [46]:
arr[0:3] = 100

In [47]:
arr

array([100, 100, 100,  47,  41,  40,  14,  11,   1,  40])

In [48]:
arr[0:5] = 50

In [49]:
arr

array([50, 50, 50, 50, 50, 40, 14, 11,  1, 40])

In [50]:
arr2 = arr.copy()

In [51]:
arr2

array([50, 50, 50, 50, 50, 40, 14, 11,  1, 40])

In [52]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

In [53]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [54]:
arr_2d[1]

array([20, 25, 30])

In [55]:
arr_2d[1][1]

25

In [57]:
arr_2d[1,1]

25

In [58]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [59]:
arr_2d[2,:]

array([35, 40, 45])

In [60]:
arr = np.arange(0,11)

In [61]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [64]:
bool_arr =  arr >  3

In [65]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True,  True])

In [67]:
arr[bool_arr]

array([ 4,  5,  6,  7,  8,  9, 10])

In [69]:
arr[arr > 3]

array([ 4,  5,  6,  7,  8,  9, 10])

In [70]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [71]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [72]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [73]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [74]:
arr * 10

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [75]:
arr / arr

C:\Users\vish\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [76]:
1 / arr

C:\Users\vish\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [77]:
arr.max()

10

In [78]:
np.max(arr)

10

In [79]:
np.log(arr)

C:\Users\vish\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

In [80]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [81]:
np.cos(arr)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
        0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026,
       -0.83907153])